include: package:flutter_lints/flutter.yaml

# Добавляем правила линтера

linter:
  rules:
    - always_declare_return_types # Обязательное указание возвращаемого типа
    - annotate_overrides # Указывать переопределённые функции
    - avoid_print # Не забыть удалить принты
    - avoid_types_as_parameter_names # Не забываем указывать тип данных
    - prefer_relative_imports # Относительные импорты в пределах пакета
    - prefer_single_quotes # Одинарные кавычки
    - use_super_parameters # Красивый конструктор
